name: Dev CI/CD
run-name: Dev pipeline triggered by ${{ github.actor }}
on:
  push:
    branches: [dev]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  run-snowflake-test-dbt-job:
    name: "Test and Deploy to Dev"
    runs-on: ubuntu-latest
    environment: prod # Must match the OIDC subject's environment
    env:
      SNOWFLAKE_CLI_FEATURES_ENABLE_DBT: true
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      # SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PAT }} # Snowflake password is required if you aren't using OIDC
      SNOWFLAKE_DATABASE: ${{ vars.SNOWFLAKE_DATABASE }}
      SNOWFLAKE_SCHEMA: ${{ vars.SNOWFLAKE_SCHEMA }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install Snowflake CLI
        uses: snowflakedb/snowflake-cli-action@v2.0
        with:
          use-oidc: true

      - name: Check Snowflake CLI Version
        run: snow --version

      - run: snow connection test -x

      - name: Deploy dbt project to dev environment
        if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
        run: snow dbt deploy tasty_bytes_dbt_dev --source ./tasty_bytes --dbt-version 1.10.15 --force -x

      - name: List all dbt project objects
        run: snow dbt list -x

      - name: Build models in dev
        run: snow dbt execute -x tasty_bytes_dbt_dev run --target dev

      - name: Run source and singular tests
        run: snow dbt execute -x tasty_bytes_dbt_dev test --target dev
